### PR TITLE
Issue #52

### PR DESCRIPTION
**Pull request by jghibiki**
Could use a decent amount of cleaning up, but this PR would add an asyncio based event loop, and defines a `builtin` module, and `plugin` module pattern. Additionally, it implements an asynchronous text input method, and an asynchronous command dispatch pattern with support for arbitrarily defined commands.

Builtin modules can be defined by adding a new module similar to `msa/builtins/command`
Third party plugins can be defined by adding a new module similar to `msa/plugins/conversation` . This plugin in particular demonstrates how the event pipeline can be used to define new commands.

Finally if you run the code you will notice that it annoyingly keeps printing "hello world" interleaved with other text output. This to show that individually defined module coroutines run independent of one another. Interaction is done through using the supervisor to propagate events to the other coroutines. Thus achieving the effect of threads without using threads at all. Blocking tasks can still be run in executor threads which asyncio helps to spawn and manage for you via `loop.run_in_executor`

### CODE REVIEW

**Comment by jghibiki** [comment]
Description of processes:
1. __main__.main() invokes supervisor.init()
  - this method loads a list of builtin modules as well as plugin modules from a list. The strings in each list should correspond to module names in `msa.builtins` and `msa.plugins` respectively.
2. __main__.main() invokes __main__.start()
  - the main_coro() function is called and the event loop is started.
3. main_coro() enqueues all the coroutines exported by each builtin or plugin module, and inserts the resulting primed coroutines into the event loop.
4. Asynchronously, each module's coroutines will be called and executed. Each `msa.couritine.Coroutine` object should have a`work()` method. If the coroutine should be executed repeatedly it should be decorated with `msa.coroutine.reschedule` which will handle rescheduling the coroutine's `work` method.
5. All I/O shoild be implemented as non-blocking, signaling between modules should be done by propogating custom events via `supervisor.propogate_event` which will add the event to each coroutine's dedicated event_queue (a `asyncio.Queue`,  there is also a priority queue type which could be used as well) 
6. Module's `coroutine.work` method should await the event_queue as needed to wait for a new event to be propogated to it. At the moment event types are checked with `isinstance` however i think some form of persistent unique id based event type checking would be preferable long term to upport other kinds of clients.

That is the gist of it. The `terminal_input`, `command`, and `help` builtins are all self contained and implemented using this pattern. The `conversation` plugin makes use of the builtins to implement a basic conversation.

Finally for listing availiable commands try `help` after starting the system..

**Comment by jghibiki** [comment]
I will add a `quit` command builtin in a bit, as i realized this had not ocurred to be until now.

**Comment by jghibiki** [comment]
Quit command added

**Comment by jghibiki** [comment]
Seems to be an issue with windows and using file descriptors: https://stackoverflow.com/a/28643127

**Comment by jghibiki** [comment]
Something else to consider. Using this architecture, I was able to - fairly easily, and with few modifications - add a client-server mode wherein two instances of the msa are started, one in server mode, and one in client mode. Then, the client is able to send commands over to the server where they are handled on the server and then events are propagated back to the client. From the client perspective, it appears as though the commands are being executed locally.

This is accomplished by adding a websocket server-client setup, and then tagging each builtin/plugin module with what modes it is allowed to run in. This allows the server to start all the modules, whereas the client is only running as subset - deferring instead to sending events to the server to be handled. This architecture would allow for clients to be implemented in anything that supports websockets (websockets was chosen so that javascript is an option, which might be useful for creating a mobile client).

[View the set of changes to enable this here](https://github.com/jghibiki/moe-serifu-agent/compare/issue55...jghibiki:feature_socket_server?expand=1)

**Comment by dekarrin** [comment]
I think we might need to take this PR offline; there's a number of architectural shifts away from the current arch that I think we need to align on.

Currently, our plan is to ensure feature parity with the current C++ codebase. We are attempting to maintain the existing architecture as well. While we are certainly not opposed to changing up the design, and while I expected this one in particular to diverge somewhat from the current EDT architecture, there seems to be several other things that have been moved about as well.

Before proceeding with this PR, I want to regroup and talk about the future direction of architecture, I'm not comfortable with merging this level of architectural changes into the master branch. On the other hand, I also don't want to lose it and stop your progress. Perhaps instead of committing directly to master, we could have a working branch that this would fit well into, in the meantime?

**Pull request merged**
