### PR TITLE
MAJOR UPDATE

### PR DESCRIPTION
**Pull request by matt-fevold**
just squidding

### CODE REVIEW

**Comment by jghibiki** [comment]
c9b57a4a0d61ccb34f59ad93b4ce0001

**Comment by dekarrin** [comment]
Levels of squid currently too high. Please review kemonomimi guidelines and add additional nekomimi to balance.

**Comment by jghibiki** [comment]
octo-cat

Does squid-cat work? I hear it is the cousin of octocat which is the Github mascot. :D

**Comment by dekarrin** [comment]
Ehh getting there but still missing yandere. Please add yandere as well.

**Comment by jghibiki** [comment]
Done. 
maxresdefault

**Comment by dekarrin** [comment]
I am seriously wondering how far we are gonna take this. Welp, may as well see what happens.

We will need additional kemonomimi in order to proceed as planned. Please add kemonomimi, preferably some "nya-nya", "wan-wan", and "kon-kon".

**Comment by jghibiki** [comment]
untitled

**Comment by dekarrin** [comment]
Please note that seafaring ships do not fulfill A/C of "Being Best Girl"; while Kancolle does fulfill previously mentioned-requirements, the A/C it breaks is pretty mission-critical. We will need fewer boats and boat-related accessories, please.

**Comment by jghibiki** [comment]
untitled


Done

**Comment by dekarrin** [comment]
I don't even know you anymore.

A/C has been fulfilled, this is just about ready to be added. One of the last things we have to do is to add the dragon loli. Please note that lewding is explicitly prohibited by coding style guideline number 17, "Ravioli Ravioli Do not Lewd the Dragon Loli" at this time, and will result in instant rejection of the PR.

**Comment by dekarrin** [comment]
As there has still been no dragon loli, I'm voting to close this PR as unmerged

**Comment by jghibiki** [comment]
image

**Comment by dekarrin** [comment]
I would love to re-examine this but the original repo seems to be gone :c

I would have merged it too, I was ready to hit the button and everything

**Comment by jghibiki** [comment]
Are you creating a new repo for the project?

**Pull request closed without merging**
